name = "ConjugateGradients"
uuid = "f59de78d-195d-4e7b-a078-2e47da4c3ad6"
authors = ["Matt Covalt <matt@kiwiziti.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
